


CONFIG_KNOWN_SYSTEM_FIELDS = {
    'Respondent.': { '_': 'Respondent.', 'include': '', 'exclude': '', 'shortname': '', 'label': '', 'format': '', 'markup': '', },
    'Respondent.Serial': { '_': 'Respondent.Serial', 'include': 'x', 'exclude': '', 'shortname': 'Respondent_Serial', 'label': '', 'format': '', 'markup': '', },
    'Respondent.ID': { '_': 'Respondent.ID', 'include': 'x', 'exclude': '', 'shortname': 'Respondent_ID', 'label': '', 'format': '', 'markup': 'id', },
    'DataCollection.': { '_': 'DataCollection.', 'include': '', 'exclude': '', 'shortname': '', 'label': '', 'format': '', 'markup': '', },
    'DataCollection.Status': { '_': 'DataCollection.Status', 'include': 'x', 'exclude': '', 'shortname': 'DataCollection_Status[L0]', 'label': 'Status - {L0}', 'format': '', 'markup': '', },
    'DataCollection.StartTime': { '_': 'DataCollection.StartTime', 'include': 'x', 'exclude': '', 'shortname': 'DataCollection_StartTime', 'label': 'Interview start time', 'format': '', 'markup': '', },
    'DataCollection.FinishTime': { '_': 'DataCollection.FinishTime', 'include': 'x', 'exclude': '', 'shortname': 'DataCollection_FinishTime', 'label': 'Interview finish time', 'format': '', 'markup': '', },
    'DataCollection.Removed': { '_': 'DataCollection.Removed', 'include': '', 'exclude': '', 'shortname': '', 'label': '', 'format': '', 'markup': '', },
    'DataCollection.InterviewMode': { '_': 'DataCollection.InterviewMode', 'include': 'x', 'exclude': '', 'shortname': 'DataCollection_InterviewMode', 'label': 'Interview Mode', 'format': '', 'markup': '', },
    'QuotaDaily': { '_': 'QuotaDaily', 'include': 'x', 'exclude': '', 'shortname': '', 'label': 'QuotaDaily', 'format': '', 'markup': '', },
    'QuotaMonthly': { '_': 'QuotaMonthly', 'include': 'x', 'exclude': '', 'shortname': '', 'label': 'QuotaMonthly', 'format': '', 'markup': '', },
    'QuotaYearly': { '_': 'QuotaYearly', 'include': 'x', 'exclude': '', 'shortname': '', 'label': 'QuotaYearly', 'format': '', 'markup': '', },
    'CensusRegion': { '_': 'CensusRegion', 'include': 'x', 'exclude': '', 'shortname': '', 'label': 'CensusRegion', 'format': '', 'markup': '', },
    'PrelimBanner': { '_': 'PrelimBanner', 'include': 'x', 'exclude': '', 'shortname': '', 'label': 'PrelimBanner', 'format': '', 'markup': '', },
    'COMP': { '_': 'COMP', 'include': 'x', 'exclude': '', 'shortname': '', 'label': 'COMP', 'format': '', 'markup': '', },
    'DelayTermReasons': { '_': 'DelayTermReasons', 'include': 'x', 'exclude': '', 'shortname': 'DelayTermReasons_[L0z3]', 'label': 'DelayTermReasons - {L0}', 'format': '', 'markup': '', },
    'CompletedScreener': { '_': 'CompletedScreener', 'include': 'x', 'exclude': '', 'shortname': '', 'label': 'CompletedScreener', 'format': '', 'markup': '', },
    'WeightingStatus': { '_': 'WeightingStatus', 'include': 'x', 'exclude': '', 'shortname': 'WeightingStatus_[L0z3]', 'label': 'WeightingStatus - {L0}', 'format': '', 'markup': '', },
    'QCData.': { '_': 'QCData.', 'include': '', 'exclude': '', 'shortname': '', 'label': '', 'format': '', 'markup': '', },
    'QCData.ErrorMsg': { '_': 'QCData.ErrorMsg', 'include': '', 'exclude': '', 'shortname': '', 'label': '', 'format': '', 'markup': '', },
    'QCData.Flags': { '_': 'QCData.Flags', 'include': 'x', 'exclude': '', 'shortname': 'QCFlags_[L0z3]', 'label': 'QCData.Flags - {L0}', 'format': '', 'markup': '', },
    'QCData.Number': { '_': 'QCData.Number', 'include': 'x', 'exclude': '', 'shortname': 'QCFlagCount', 'label': 'QCData.Number', 'format': '', 'markup': '', },
    'USLocationData.': { '_': 'USLocationData.', 'include': '', 'exclude': '', 'shortname': '', 'label': '', 'format': '', 'markup': '', },
    'USLocationData.Zip': { '_': 'USLocationData.Zip', 'include': 'x', 'exclude': '', 'shortname': 'USLoc_Zip', 'label': 'USLocationData.Zip', 'format': '', 'markup': '', },
    'USLocationData.State': { '_': 'USLocationData.State', 'include': 'x', 'exclude': '', 'shortname': 'USLoc_State', 'label': 'USLocationData.State', 'format': '', 'markup': '', },
    'USLocationData.CensusRegion': { '_': 'USLocationData.CensusRegion', 'include': 'x', 'exclude': '', 'shortname': 'USLoc_Region', 'label': 'USLocationData.CensusRegion', 'format': '', 'markup': '', },
    'USLocationData.NielsenDMAText': { '_': 'USLocationData.NielsenDMAText', 'include': 'x', 'exclude': '', 'shortname': 'USLoc_NielsenDMA', 'label': 'USLocationData.NielsenDMAText', 'format': '', 'markup': '', },
    'USLocationData.NielsenCountySize': { '_': 'USLocationData.NielsenCountySize', 'include': 'x', 'exclude': '', 'shortname': 'USLoc_NielsenCountySize', 'label': 'USLocationData.NielsenCountySize', 'format': '', 'markup': '', },
}
